NetworkProject/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^network/', include('network.urls')),
    url(r"^search/", include("watson.urls", namespace="watson")),
    url(r'^messages/', include('postman.urls')),

]+static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

network/urls.py
from django.conf.urls import patterns, url
from network import views

urlpatterns = patterns('',

                       url(r'^login/$', views.login, name='login'),
                       url(r'^logout/$', views.logout, name='logout'),

                       url(r'^home/$', views.index, name='index'),

                       url(r'^test2/$', views.test2, name='index'),

                       url(r'^user/(?P<user_id>[\w\-]+)/$', views.getuser, name='getuser'),
                       url(r'^user/(?P<user_id>[\w\-]+)/newacademic/$', views.user_academic, name='getuser'),
                       url(r'^university/(?P<university_slug>[-\w]+)/$', views.university, name='university'),
                       url(r'^university/(?P<university_slug>[\w\-]+)/faculty/(?P<faculty_slug>[\w\-]+)/$',
                           views.faculty, name='faculty'),
                       url(r'^university/(?P<university_slug>[\w\-]+)/department/(?P<department_slug>[\w\-]+)/$',
                           views.department, name='department'),
                       url(r'^university/(?P<university_slug>[\w\-]+)/course/(?P<course_slug>[\w\-]+)/$',
                           views.course, name='course'),

                       url(r'^university/(?P<university_slug>[\w\-]+)/course/(?P<course_slug>[\w\-]+)/section/(?P<section_no>[\w\-]+)/$',
                           views.section, name='section'),

                       url(r'^test/$', views.test, name='index'),
                       url(r'^submit/$', views.new_feed, name='submit'),
                       url(r'^addcoursework/$', views.new_coursework, name='new cw'),
                       url(r'^getsections/$', views.get_sections, name='get_sections'),
                       url(r'^getfaculties/$', views.get_faculty, name='get_faculty'),
                       url(r'^getdepartments/$', views.get_department, name='get_department'),



                       url(r'^register/lecturer/$', views.lecturer_register, name='lecturer_register'),
                       url(r'^register/student/$', views.student_register, name='student_register'),
                       url(r'^register/university/$', views.university_register, name='university_register'),
                       url(r'^register/faculty/$', views.faculty_register, name='faculty_register'),
                       url(r'^register/department/$', views.department_register, name='department_register'),
                       url(r'^register/course/$', views.course_register, name='course_register'),

                       url(r'^university/(?P<university_slug>[\w\-]+)/course/(?P<course_slug>[\w\-]+)/addsection/$',
                           views.add_section, name='addsection'),
                       url(r'^feed/(?P<feed_id>[\w\-]+)/addcomment/$', views.add_comment, name='addcomment'),
                       )

network/models.py
import os
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin
from django.template.defaultfilters import slugify
from django.core.validators import MaxValueValidator, MinValueValidator
from django.core.validators import RegexValidator
import datetime
from django.utils.timezone import utc
import watson

year_regex = RegexValidator(regex=r'^\d{4}$')


class CustomUser(AbstractBaseUser, PermissionsMixin):
    # Custom user class
    email = models.EmailField(
        verbose_name='email address',
        unique=True,
        max_length=255
    )
    user_id = models.CharField(unique=True, max_length=10, null=True)
    date_joined = models.DateTimeField(auto_now_add=True)
    profile_picture = models.ImageField(upload_to='profile_pics', null=True, blank=True)

    is_lecturer = models.BooleanField(default=False)
    is_student = models.BooleanField(default=False)

    is_active = models.BooleanField(default=True)
    is_admin = models.BooleanField(default=False)

    USERNAME_FIELD = 'email'

    def __unicode__(self):
        return self.email

    def get_full_name(self):
        return self.email

    def get_short_name(self):
        return self.email

    def has_perm(self, perm, obj=None):
        "Does the user have a specific permission?"
        # Simplest possible answer: Yes, always
        return True

    def has_module_perms(self, app_label):
        "Does the user have permissions to view the app `app_label`?"
        # Simplest possible answer: Yes, always
        return True

    @property
    def is_staff(self):
        "Is the user a member of staff?"
        # Simplest possible answer: All admins are staff
        return self.is_admin


class Academic(models.Model):
    user = models.ForeignKey(CustomUser, null=True, blank=True)
    degree = models.CharField(max_length=10)
    field = models.CharField(max_length=50)
    institution = models.CharField(max_length=50)
    year = models.CharField(validators=[year_regex], max_length=4)


class Publication(models.Model):
    user = models.ForeignKey(CustomUser, null=True, blank=True)
    title = models.CharField(max_length=100)
    authors = models.CharField(max_length=100)
    year = models.CharField(validators=[year_regex], max_length=4)
    reference = models.CharField(max_length=250)
    link = models.URLField(max_length=100, null=True, blank=True)


class Professional(models.Model):
    user = models.ForeignKey(CustomUser, null=True, blank=True)
    company = models.CharField(max_length=100)
    position = models.CharField(max_length=100)
    description = models.CharField(max_length=1000)
    start = models.CharField(max_length=50)
    end = models.CharField(max_length=50)


class University(models.Model):

    name = models.CharField(max_length=80, unique=True)
    shortname = models.CharField(max_length=15, unique=True, null=True, blank=True)
    university_slug = models.SlugField(unique=True, null=True, blank=True)

    profile_picture = models.ImageField(upload_to='profile_pics', null=True, blank=True)

    website = models.URLField(max_length=50, null=True, blank=True)
    general_info = models.CharField(max_length=1000, null=True, blank=True)
    contact_info = models.CharField(max_length=400, null=True, blank=True)
    location = models.CharField(max_length=100, null=True, blank=True)
    established = models.CharField(validators=[year_regex], max_length=4, null=True, blank=True)

    def save(self, *args, **kwargs):

        if self.shortname is None:
            self.university_slug = slugify(self.name)
        else:
            self.university_slug = slugify(self.shortname)
        super(University, self).save(*args, **kwargs)

    def __unicode__(self):
        return self.name

watson.register(University.objects.all(), fields=("name", "shortname","location"))

class Faculty(models.Model):

    name = models.CharField(max_length=80)
    shortname = models.CharField(max_length=15, null=True, blank=True)
    faculty_slug = models.SlugField(null=True, blank=True)
    website = models.URLField(max_length=50, null=True, blank=True)
    information = models.CharField(max_length=1000, null=True, blank=True)

    university = models.ForeignKey(University)

    class Meta:
        unique_together = (("university", "name"),)

    def save(self, *args, **kwargs):
        if self.shortname is None:
            self.faculty_slug = slugify(self.name.lower())
        else:
            self.faculty_slug = slugify(self.shortname.lower())
        super(Faculty, self).save(*args, **kwargs)

    def __unicode__(self):
        return self.name


class Department(models.Model):

    name = models.CharField(max_length=50)
    shortname = models.CharField(max_length=15, null=True, blank=True)
    department_slug = models.SlugField(null=True, blank=True)
    information = models.CharField(max_length=1000, null=True, blank=True)
    website = models.URLField(max_length=50, null=True, blank=True)

    faculty = models.ForeignKey(Faculty)

    class Meta:
        unique_together = (("faculty", "name"),)

    def save(self, *args, **kwargs):
        if self.shortname is None:
            self.department_slug = slugify(self.name.lower())
        else:
            self.department_slug = slugify(self.shortname.lower())
        super(Department, self).save(*args, **kwargs)

    def __unicode__(self):
        return self.name


class Course(models.Model):

    code = models.CharField(primary_key=True, max_length=10)
    course_slug = models.SlugField(null=True, blank=True)
    description = models.CharField(max_length=75, null=True, blank=True)
    info = models.CharField(max_length=1000, null=True, blank=True)
    grading = models.CharField(max_length=300, null=True, blank=True)
    semester = models.CharField(max_length=25)
    credits = models.IntegerField(null=True, blank=True)

    department = models.ForeignKey(Department)

    prerequisites = models.ManyToManyField("self", null=True, blank=True)

    def save(self, *args, **kwargs):
        self.course_slug = slugify(self.code.lower())
        super(Course, self).save(*args, **kwargs)

    def __unicode__(self):
        return self.code


class Section(models.Model):

    course = models.ForeignKey(Course)
    section_no = models.CharField(max_length=10)

    class Meta:
        unique_together = (("course", "section_no"),)

    def __unicode__(self):
        return "%s %s" % (self.course, self.section_no)


class LocationTime(models.Model):
    section = models.ForeignKey(Section, null=True, blank=True)
    location = models.CharField(max_length=300)
    time = models.TimeField(blank=True)


class Lecturer(models.Model):

    user = models.OneToOneField(CustomUser, related_name='lecturer')

    name = models.CharField(max_length=50)
    surname = models.CharField(max_length=50)
    website = models.URLField(max_length=50, null=True, blank=True)

    academic_rank = models.CharField(max_length=50,)
    admin_rank = models.CharField(max_length=50, null=True, blank=True)

    sections = models.ManyToManyField(Section, related_name="lecturer")
    department = models.ForeignKey(Department, null=True, blank=True)

    def __unicode__(self):
        return "%s %s" % (self.name, self.surname)


class Assistant(models.Model):

    user = models.OneToOneField(CustomUser, related_name='assistant')

    name = models.CharField(max_length=50)
    surname = models.CharField(max_length=50)
    website = models.URLField(max_length=50, null=True, blank=True)

    lecturing_sections = models.ManyToManyField(Section, related_name="assistants")
    attending_sections = models.ManyToManyField(Section, related_name="assistant_students")

    def __unicode__(self):
        return "%s %s" % (self.name, self.surname)


class Student(models.Model):

    EDU_TYPE = (
        ('Yüksek Lisans', 'Yüksek Lisans'),
        ('Lisans', 'Lisans'),
    )

    user = models.OneToOneField(CustomUser, related_name='student')

    name = models.CharField(max_length=50)
    surname = models.CharField(max_length=50)
    website = models.URLField(max_length=50, null=True, blank=True)

    education = models.CharField(max_length=50, choices=EDU_TYPE, default='Graduate')

    sections = models.ManyToManyField(Section, related_name="students")
    departments = models.ManyToManyField(Department)

    def __unicode__(self):
        return "%s %s" % (self.name, self.surname)


class CommentContainer(models.Model):
    cont_id = models.CharField(unique=True, max_length=10, null=True)


class Comment(models.Model):

    container = models.ForeignKey(CommentContainer, null=True, blank=True)
    content = models.CharField(max_length=280)
    creator = models.ForeignKey(CustomUser, null=True, blank=True)
    creation_date = models.DateTimeField(auto_now=True, blank=True)


class Feed(models.Model):

    creator = models.ForeignKey(Lecturer, null=True, blank=True)
    section = models.ForeignKey(Section, null=True, blank=True)

    container = models.ForeignKey(CommentContainer, null=True, blank=True)

    content = models.CharField(max_length=280)
    creation_date = models.DateTimeField(auto_now=True)
    feed_id = models.CharField(unique=True, max_length=10, null=True)
    attachment = models.FileField(upload_to='attachments', blank=True, null=True)

    def filename(self):
        return os.path.basename(self.attachment.name)

    def __unicode__(self):
        return "%s %s" % (self.section, self.content)





class CourseWork(models.Model):

    SUBMISSION_OPTIONS = (
        ('In class', 'In class'),
        ('Online', 'Online'),
    )

    section = models.ForeignKey(Section, null=True, blank=True)
    creation_date = models.DateTimeField(auto_now=True, null=True)
    coursework_id = models.CharField(unique=True, max_length=10, null=True)
    title = models.CharField(max_length=30)
    description = models.CharField(max_length=75)

network/templates/network/base.html
<!DOCTYPE html>
<html>
{% load staticfiles %}
<head lang="en">
    <title>Network</title>
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
    <link href="//netdna.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/jasny-bootstrap/3.1.3/css/jasny-bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="{% static 'network/style.css' %}" />
</head>
<body>
    <div>
        {% block body_block %}{% endblock %}
    </div>
</body>
    <script src="https://code.jquery.com/jquery-1.10.2.min.js"></script>
    <script src="//netdna.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/jasny-bootstrap/3.1.3/js/jasny-bootstrap.min.js"></script>
    <script type="text/javascript" src="{% static 'network/main.js' %}"></script>
</html>

network/templates/network/base2.html
<!DOCTYPE html>
<html>
{% load staticfiles %}
<head lang="en">
    <!--
    <title>New Layout</title>
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
    <link href="//netdna.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/jasny-bootstrap/3.1.3/css/jasny-bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="{% static 'network/style2.css' %}" />

    <script src="//code.jquery.com/jquery-1.11.3.min.js"></script>
    <script src="//code.jquery.com/jquery-migrate-1.2.1.min.js"></script>
    <script src="//netdna.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
    <script type="text/javascript" src="{% static 'network/main.js' %}"></script>

    {{ form.media }}
    -->
    <link href="//netdna.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'network/style2.css' %}" />
    <script src="//code.jquery.com/jquery-1.11.3.min.js"></script>
    <script src="//code.jquery.com/jquery-migrate-1.2.1.min.js"></script>
    <script src="//netdna.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
    <script type="text/javascript" src="{% static 'network/main.js' %}"></script>
    {{ form.media }}
</head>
<body>
<div id="main-cont">
    <div id="navbar">
        {% if user.is_authenticated %}
            <div id="top-nav-cont">
                <div class="top-nav-opt" id="f-tab">
                    <a href="/network/home/"><span style="color: #666666;line-height: 43px;">Feed</span></a>
                </div>
                <div class="top-nav-opt" id="c-tab">
                     <a href="/network/test/"><span style="color: #666666;line-height: 43px;">Coursework</span></a>
                </div>
            </div>
        {% endif %}
    </div>
    {% block body_block %}

    {% endblock %}
</div>
</body>

</html>

network/templates/network/course.html
{% extends 'network/base2.html' %}
{% load staticfiles %}
{% load bootstrap %}
{% load thumbnail %}

{% block body_block %}

    <div id="user-basic-info">

        <div id="user-name">
            {{ course.code }}
        </div>
        <div id="user-academic-rank">
            {{ course.description }}
        </div>
        <hr style="margin-top: 10px; margin-bottom: 10px;">
        <div id="user-university">
            <span style="color: #cccccc;"><i class="fa fa-map-marker"></i></span> {{ course.university }} / {{ course.department }}
        </div>
        <br>
        <div id="user-university">
            <span style="color: #cccccc;"><i class="fa fa-map-marker"></i></span>Prerequisites:{% for p in course.rerequisites %}  {{ p.code }} {% endfor %}
        </div>


        <hr style="margin-top: 10px; margin-bottom: 10px;">

        <div id="user-count">
            <div id="stu-count">
                <span style="font-size:27px;line-height: 24px;color:#4183c4;font-weight: bold;">{{ course.credits }}</span>
                <br/>
                <span style="font-size:14px;line-height: 20px;color:#777777;">Credits</span>
            </div>

            <div id="cor-count">
                <span style="font-size:27px;line-height: 24px;color:#4183c4;font-weight: bold;">{{ section_count }}</span>
                <br/>
                <span style="font-size:14px;line-height: 20px;color:#777777;">Sections</span>
            </div>
        </div>


    </div>
    <div id="user-more-info">
        <div class="academic-cont">
            <div class="academic-top">
                <div class="more-info-header">
                    Course Info
                </div>
                <div class="more-info-btn">

                </div>
                <div class="pub-obj">
                    <span style="font-size: 15px;line-height: 23px;color: #555555;"><p>
                        {{ course.info }}
                    </p></span>
                </div>
            </div>
        </div>
        <div class="teaching-cont">
            <div class="teaching-top">
                <div class="more-info-header">
                    Grading
                </div>
                <div class="more-info-btn">

                </div>
                <div>
                    <span style="font-size: 15px;line-height: 23px;color: #555555;"><p>
                        {{ course.grading }}
                    </p></span>
                </div>

            </div>
        </div>
        <div class="pub-cont">
            <div class="pub-top">
                <div class="more-info-header">
                    Sections
                </div>
                <div class="more-info-btn">

                </div>
                {% for s in sections %}
                <div class="pub-obj">
                    Section {{ s.section_no }}
                    Instructor: {{ s.lecturer_set.all }}
                </div>
                {% endfor %}
            </div>
        </div>

    </div>
{% endblock %}

network/templates/network/createcourse.html
{% extends 'network/base.html' %}

{% load bootstrap %}

{% block title %}New course{% endblock %}

{% block body_block %}
    <div class="container">
        <form id="form" method="post" action="/network/register/course/" enctype="multipart/form-data">
            {% csrf_token %}
            {{c_form|bootstrap}}
            <div class="form-group">
                <button type="submit" class="btn btn-sample btn-sm ">Register</button>
            </div>
        </form>
    </div>
{% endblock %}

network/templates/network/createfaculty.html
{% extends 'network/base.html' %}

{% load bootstrap %}

{% block title %}New faculty{% endblock %}

{% block body_block %}
    <div class="container">
        <form id="form" method="post" action="/network/register/faculty/" enctype="multipart/form-data">
            {% csrf_token %}
            {{f_form|bootstrap}}
            <div class="form-group">
                <button type="submit" class="btn btn-sample btn-sm ">Register</button>
            </div>
        </form>
    </div>
{% endblock %}

network/templates/network/department.html
{% extends 'network/base2.html' %}
{% load staticfiles %}
{% load bootstrap %}
{% load thumbnail %}

{% block body_block %}

    <div id="user-basic-info">

        <div id="user-name">
            {{ department.name }}
        </div>
        <div id="user-academic-rank">
            {{ department.faculty.university }}
        </div>
        <hr style="margin-top: 10px; margin-bottom: 10px;">
        <div id="user-university">
            <span style="color: #cccccc;"><i class="fa fa-map-marker"></i></span> Istanbul / Turkey
        </div>
        <a href="/network/home/"><span style="color: #4183c4;line-height: 43px;">cse.yeditepe.edu.tr</span></a>

        <hr style="margin-top: 10px; margin-bottom: 10px;">

        <div id="user-count">
            <div id="stu-count">
                <span style="font-size:27px;line-height: 24px;color:#4183c4;font-weight: bold;">{{ student_count }}</span>
                <br/>
                <span style="font-size:14px;line-height: 20px;color:#777777;">Students</span>
            </div>

            <div id="cor-count">
                <span style="font-size:27px;line-height: 24px;color:#4183c4;font-weight: bold;">{{ courses.count }}</span>
                <br/>
                <span style="font-size:14px;line-height: 20px;color:#777777;">Courses</span>
            </div>
        </div>


    </div>
    <div id="user-more-info">
        <div class="academic-cont">
            <div class="academic-top">
                <div class="more-info-header">
                    General Info
                </div>
                <div class="more-info-btn">

                </div>
                <div class="pub-obj">
                    <span style="font-size: 15px;line-height: 23px;color: #555555;"><p>
                      {{ department.info }}
                    </p></span>
                </div>
            </div>
        </div>
        <div class="teaching-cont">
            <div class="teaching-top">
                <div class="more-info-header">
                    Members
                </div>
                <div class="more-info-btn">

                </div>
            </div>
            {% for l in lecturers %}
                    <div class="teach-obj">
                        <div class="avatar">
                            <img src="{{ l.user.profile_picture|thumbnail_url:'avatar-small' }}" alt="" />
                        </div>
                        {{ l.name }}{{ l.surname }}
                        {{ l.academic_rank }}
                    </div>
                {% endfor %}
        </div>
        <div class="pub-cont">
            <div class="pub-top">
                <div class="more-info-header">
                    Courses
                </div>
                <div class="more-info-btn">

                </div>
            </div>
            {% for c in courses %}
                    <div class="teach-obj">
                    {{ c.code }}
                    {{ c.description }}
                    </div>
                {% endfor %}
        </div>

    </div>
{% endblock %}

network/templates/network/faculty.html
{% extends 'network/base2.html' %}
{% load staticfiles %}
{% load bootstrap %}
{% load thumbnail %}

{% block body_block %}

    <div id="user-basic-info">

        <div id="user-name">
            {{ Faculty.name }} Faculty
        </div>
        <div id="user-academic-rank">
            {{ faculty.university }} University
        </div>
        <hr style="margin-top: 10px; margin-bottom: 10px;">
        <div id="user-university">
            <span style="color: #cccccc;"><i class="fa fa-map-marker"></i></span> {{ faculty.location}}
        </div>
        <a href={{ faculty.website }}><span style="color: #4183c4;line-height: 43px;">{{ faculty.website }}</span></a>

        <hr style="margin-top: 10px; margin-bottom: 10px;">

        <div id="user-count">
            <div id="stu-count">
                <span style="font-size:27px;line-height: 24px;color:#4183c4;font-weight: bold;"> {{ student_count }}</span>
                <br/>
                <span style="font-size:14px;line-height: 20px;color:#777777;">Students</span>
            </div>

            <div id="cor-count">
                <span style="font-size:27px;line-height: 24px;color:#4183c4;font-weight: bold;">{{ department_count }}</span>
                <br/>
                <span style="font-size:14px;line-height: 20px;color:#777777;">Departments</span>
            </div>
        </div>


    </div>
    <div id="user-more-info">
        <div class="academic-cont">
            <div class="academic-top">
                <div class="more-info-header">
                    General Info
                </div>
                <div class="more-info-btn">

                </div>
                <div class="pub-obj">
                    <span style="font-size: 15px;line-height: 23px;color: #555555;"><p>
                       {{ faculty.info}}
                    </p></span>
                </div>
            </div>
        </div>

        <div class="pub-cont">
            <div class="pub-top">
                <div class="more-info-header">
                    Departments
                </div>
                <div class="more-info-btn">

                </div>
                <div class="more-info-btn">
                    {% for d in departments %}
                        <div class="faculty-obj">
                            {{ d.name }}
                        </div>
                    {% endfor %}
            </div>
            </div>
        </div>

    </div>
{% endblock %}

network/templates/network/lecturerregister.html
{% extends 'network/base.html' %}

{% load bootstrap %}

{% block title %}Lecturer account{% endblock %}

{% block body_block %}
    <div class="lecturer-register-container">
        <form id="form" method="post" action="/network/register/lecturer/" enctype="multipart/form-data">
            {% csrf_token %}
            {{user_form|bootstrap}}
            <label class="control-label  " for="p_pic">Profile picture</label><br/>
            <div class="fileinput fileinput-new" data-provides="fileinput">
                <span class="btn btn-default btn-file">
                    <span class="fileinput-new">Select image</span>
                    <span class="fileinput-exists">Change</span>
                    <input type="file" name="p_pic" id="p_pic">
                </span>
                <span class="fileinput-filename"></span>
                <a href="#" class="close fileinput-exists" data-dismiss="fileinput" style="float: none">&times;</a>
            </div>
            {{lecturer_form|bootstrap}}
            <div class="form-group">
                <button type="submit" class="btn btn-sample btn-sm ">Sign up</button>
            </div>
        </form>
    </div>
{% endblock %}

network/templates/network/login.html
{% extends 'network/base.html' %}

{% load bootstrap %}

{% block title %}Sign in{% endblock %}

{% block body_block %}
    <div class="container">
        <form id="login_form" method="post" action="/network/login/">
            {% csrf_token %}
            {{form|bootstrap}}
            <div class="form-group">
                <button type="submit" class="btn btn-sample btn-sm ">Sign In</button>
            </div>
        </form>
    </div>
{% endblock %}

network/templates/network/studentregister.html
{% extends 'network/base.html' %}

{% load bootstrap %}

{% block title %}Student account{% endblock %}

{% block body_block %}
    <div class="container">
        <form id="form" method="post" action="/network/register/student/" enctype="multipart/form-data">
            {% csrf_token %}
            {{user_form|bootstrap}}
            {{student_form|bootstrap}}
            <div class="form-group">
                <button type="submit" class="btn btn-sample btn-sm ">Submit</button>
            </div>
        </form>
    </div>
{% endblock %}

network/templates/network/university.html
{% extends 'network/base2.html' %}
{% load staticfiles %}
{% load bootstrap %}
{% load thumbnail %}

{% block body_block %}

    <div id="user-basic-info">
        <img src="{{p_pic}}" alt="" />
        </br>
        <div id="user-name">
            {{ university.name }} University
        </div>
        <hr style="margin-top: 10px; margin-bottom: 10px;">
        <div id="user-university">
            <span style="color: #7b8084;">{{ university.location }}</span>
        </div>
        <a href={{ university.website }}><span style="color: #4183c4;line-height: 43px;">{{ university.website }}</span></a>
        <p>Established: {{ university.established }}<p/>
        <hr style="margin-top: 10px; margin-bottom: 10px;">

        <div id="user-count">
            <div id="stu-count">
                <span style="font-size:27px;line-height: 24px;color:#4183c4;font-weight: bold;">{{ student_count }}</span>
                <br/>
                <span style="font-size:14px;line-height: 20px;color:#777777;">Students</span>
            </div>

            <div id="cor-count">
                <span style="font-size:27px;line-height: 24px;color:#4183c4;font-weight: bold;">{{ faculty_count }}</span>
                <br/>
                <span style="font-size:14px;line-height: 20px;color:#777777;">Faculties</span>
            </div>
        </div>


    </div>
    <div id="user-more-info">
        <div class="academic-cont">
            <div class="academic-top">
                <div class="more-info-header">
                    General Info
                </div>
                </div>
                <div class="pub-obj">
                    <span style="font-size: 15px;line-height: 23px;color: #555555;"><p>{{ university.general_info }}</p></span>
                </div>

        </div>
        <div class="teaching-cont">
            <div class="teaching-top">
                <div class="more-info-header">
                    Contact Info
                </div>
            </div>

            <div class="teach-obj">
                <span style="font-size: 15px;line-height: 23px;color: #555555;"><p>{{ university.contact_info }}</p></span>
            </div>

        </div>
        <div class="pub-cont">
            <div class="teaching-top">
                <div class="more-info-header">
                    Faculties
                </div>
            </div>
            <div class="more-info-btn">
                    {% for f in faculties %}
                        <div class="faculty-obj">
                            {{ f.name }}
                            {{ f.website }}
                            {{ f.info }}
                        </div>
                    {% endfor %}
            </div>
        </div>
    </div>
{% endblock %}